export const KEYBOARD_LAYOUT = [
  {
    id: "row1",
    keys: [
      { id: "1", name: "`", code: "Backquote" },
      { id: "2", name: "1", code: "Digit1" },
      { id: "3", name: "2", code: "Digit2" },
      { id: "4", name: "3", code: "Digit3" },
      { id: "5", name: "4", code: "Digit4" },
      { id: "6", name: "5", code: "Digit5" },
      { id: "7", name: "6", code: "Digit6" },
      { id: "8", name: "7", code: "Digit7" },
      { id: "9", name: "8", code: "Digit8" },
      { id: "10", name: "9", code: "Digit9" },
      { id: "11", name: "0", code: "Digit0" },
      { id: "12", name: "-", code: "Minus" },
      { id: "13", name: "=", code: "Equal" },
      { id: "14", name: "Delete", code: "Backspace", grow: true },
    ],
  },
  {
    id: "row2",
    keys: [
      { id: "15", name: "Tab", code: "Tab", grow: true },
      { id: "16", name: "q", code: "KeyQ" },
      { id: "17", name: "w", code: "KeyW" },
      { id: "18", name: "e", code: "KeyE" },
      { id: "19", name: "r", code: "KeyR" },
      { id: "20", name: "t", code: "KeyT" },
      { id: "21", name: "y", code: "KeyY" },
      { id: "22", name: "u", code: "KeyU" },
      { id: "23", name: "i", code: "KeyI" },
      { id: "24", name: "o", code: "KeyO" },
      { id: "25", name: "p", code: "KeyP" },
      { id: "26", name: "[", code: "BracketLeft" },
      { id: "27", name: "]", code: "BracketRight" },
      { id: "28", name: "\\", code: "Backslash" },
    ],
  },
  {
    id: "row3",
    keys: [
      { id: "29", name: "Caps Lock", code: "CapsLock", grow: true },
      { id: "30", name: "a", code: "KeyA" },
      { id: "31", name: "s", code: "KeyS" },
      { id: "32", name: "d", code: "KeyD" },
      { id: "33", name: "f", code: "KeyF" },
      { id: "34", name: "g", code: "KeyG" },
      { id: "35", name: "h", code: "KeyH" },
      { id: "36", name: "j", code: "KeyJ" },
      { id: "37", name: "k", code: "KeyK" },
      { id: "38", name: "l", code: "KeyL" },
      { id: "39", name: ";", code: "Semicolon" },
      { id: "40", name: "'", code: "Quote" },
      { id: "41", name: "Return", code: "Enter", grow: true, border: true },
    ],
  },
  {
    id: "row4",
    keys: [
      { id: "42", name: "Shift", code: "ShiftLeft", grow: true },
      { id: "43", name: "z", code: "KeyZ" },
      { id: "44", name: "x", code: "KeyX" },
      { id: "45", name: "c", code: "KeyC" },
      { id: "46", name: "v", code: "KeyV" },
      { id: "47", name: "b", code: "KeyB" },
      { id: "48", name: "n", code: "KeyN" },
      { id: "49", name: "m", code: "KeyM" },
      { id: "50", name: ",", code: "Comma" },
      { id: "51", name: ".", code: "Period" },
      { id: "52", name: "/", code: "Slash" },
      { id: "53", name: "Shift", code: "ShiftRight", grow: true },
    ],
  },
  {
    id: "row5",
    keys: [
      { id: "54", name: "Ctrl", code: "ControlLeft" },
      { id: "55", name: "Alt", code: "AltLeft" },
      { id: "56", name: "Meta", code: "MetaLeft" },
      { id: "57", name: " ", code: "Space", grow: true, border: true },
      { id: "58", name: "Meta", code: "MetaRight" },
      { id: "59", name: "Alt", code: "AltRight" },
    ],
  },
] as const;

type ActiveKeyCodes = Map<string, boolean>;
export const activeKeyCodes: ActiveKeyCodes = new Map();
